#%RAML 1.0
title: MyAPI
version: 1.0
baseUri: http://com.foo.bar/api
value:
-
  id: "1"
  firstName: "Ibrahim"
  lastName: "Gajam"
  address: "32, main street , Nigeria"
  postal: "12312"
  country: "Nigeria"
  state: "abc"
  contactNo: 123456789
  course: "MSc"
  admissionDate: 2022-12-30T14:20:67.0000Z
  type: "regular"
-
 id: "2"
   firstName: "Mirium"
   lastName: "Ilunga"
   address: "54, main street , Nigeria"
   postal: "12312"
   country: "Nigeria"
   state: "vvc"
   contactNo: 123456563
   course: "MCA"
   admissionDate: 2022-12-30T14:20:67.0000Z
   type: "regular"
